server:
  port: 10090

spring:
  application:
    name: spring-ai-ext-sql-tool-adapter

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/aiserver
    username: postgres
    password: password

  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        # use a proxy to log all calls
        # base-url: http://localhost:9092
    mcp:
      server:
        name: spring-ai-ext-sql-tool-adapter
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages